### ISSUE TITLE
Color support

### ISSUE THREAD

**Issue by UnkindPartition** [UnkindPartition/tasty#1]

**Comment by hasufell** [comment]
How to adjust the coloring? E.g. I want to keep all coloring except the one for the error messages. Tasty does not expose enough internals to write your own `consoleTestReporter` (e.g. `consoleTestReporterOptions` is not exported).

**Comment by UnkindPartition** [comment]
> Tasty does not expose enough internals to write your own consoleTestReporter

It's a short simple list, you can just copy it.

If you'd like to propose anything specific, please open a separate issue for that.
