### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by etorreborre** [UnkindPartition/tasty#218]
This is more a question than a bug report. I am trying to follow the advice in Neil Mitchell's blog post about [memory leaks](http://neilmitchell.blogspot.se/2015/09/detecting-space-leaks.html) and I get stacktraces on the following code:
![image](https://user-images.githubusercontent.com/10988/39661141-0eed6d64-504d-11e8-8c46-f7757c994e15.png)

I am not experienced enough to really understand if I'm doing it wrong or if there is a real issue lurking in there. If that's the case it is kind of annoying because it potentially hides my *own* space leaks :-). Thank you for your help

**Comment by feuerbach** [comment]
Yes, this looks legit. Unfortunately, it's not that easy to fix. We need some way to tell `Ap` to force `a`s inside `f a` in a way that works for `f = IO` but is also polymorphic over `f`.

[Unlifted data types](https://ghc.haskell.org/trac/ghc/wiki/UnliftedDataTypes) would be one way to do that, but they are not implemented yet.

I'll keep thinking about this, but I can't promise a quick resolution.

**Comment by etorreborre** [comment]
I don't understand why you use `Ap` here instead of doing a `traverse` and possibly collect the results with a `Monoid`?

**Comment by feuerbach** [comment]
You are right, in that particular case `foldMap` could probably be by `traverse`. The benefit of `Ap` is that it automatically appends the results.

In general, Ap is used in tasty to fold test trees (through `foldTestTree`); test trees are not functors. So I'd like to solve this problem in general lest it pop up somewhere else.

**Comment by etorreborre** [comment]
I don't know how I can help here. I am the author of a testing library in Scala: [specs2](http://specs2.org). The internals are structured around a stream of "Fragments" and not a tree. Then I am "folding" the stream by using `foldl`-like folds (for computing levels, print results and so on). One thing I realized was that it was possible to offer an API which allowed the creation of tests as a tree structure which was then linearized as a stream and back to a tree for reporting. I'm not saying that's what you should do but maybe that's food for thought - I can't imagine the amount of changes you would have to do to implement this approach! Fun fact, for a while I had some form of `Reducers` in my code base :-).

**Comment by etorreborre** [comment]
Closing this old issue now.
