### ISSUE TITLE
Suggest pattern to rerun an individual failing test

### ISSUE THREAD

**Issue by Bodigrim** [UnkindPartition/tasty#271]
I would like `tasty` to suggest me an appropriate `--pattern PATTERN` to rerun an individual failing test, similar to [hspec](http://hspec.github.io/match.html). Is there an ingredient available? If not, could it be implemented as a part of `ConsoleReporter` or should I go for a standalone ingredient in a separate package?

**Comment by feuerbach** [comment]
There's this one, which doesn't even require you to copy-paste a pattern: https://hackage.haskell.org/package/tasty-rerun. Does it address your need?

**Comment by feuerbach** [comment]
Ah, I just noticed that you're a maintainer of that package now, so you must be aware of it :-)

**Comment by feuerbach** [comment]
If you want to print a pattern, I think it's fine to add it to ConsoleReporter. FWIW, the correct pattern should be `$0 == "..."`, with the full test name properly escaped.

**Comment by Bodigrim** [comment]
Surprisingly this feature can be implemented separately, as an ingredient transformer:

```haskell
import Control.Monad
import Data.IntMap (IntMap)
import qualified Data.IntMap as IM
import GHC.Conc
import Test.Tasty.Ingredients
import Test.Tasty.Providers
import Test.Tasty.Runners

modifyReporter :: (TestName -> Result -> Result) -> Ingredient -> Ingredient
modifyReporter f (TestReporter desc cb) = TestReporter desc $ \opts tree ->
  let names = IM.fromDistinctAscList $ zip [0..] (testsNames opts tree)
      modifySMap = postprocessResult f . IM.intersectionWith (,) names
  in (modifySMap >=>) <$> cb opts tree
modifyReporter _ TestManager{} = error "modifyReporter cannot modify TestManager"

postprocessResult :: (TestName -> Result -> Result) -> IntMap (TestName, TVar Status) -> IO StatusMap
postprocessResult f src = do
  paired <- forM src $ \(name, tv) -> (name, tv,) <$> newTVarIO NotStarted
  let doUpdate = atomically $ do
        (Any anyUpdated, All allDone) <-
          getApp $ flip foldMap paired $ \(name, newTV, oldTV) -> Ap $ do
            old <- readTVar oldTV
            case old of
              Done{} -> pure (Any False, All True)
              _ -> do
                new <- readTVar newTV
                case new of
                  Done res -> do
                    writeTVar oldTV (Done (f name res))
                    pure (Any True, All True)
                  -- ignoring Progress nodes
                  -- it would be helpful to have instance Eq Status
                  _ -> pure (Any False, All False)
        if anyUpdated || allDone then pure allDone else retry
      adNauseam = doUpdate >>= (`unless` adNauseam)
  _ <- forkIO adNauseam
  pure $ fmap (\(_, _, a) -> a) paired

appendPatternIfFailed :: TestName -> Result -> Result
appendPatternIfFailed name res = case resultOutcome res of
  Success -> res
  -- TODO proper awk escaping
  Failure{} -> res { resultDescription = resultDescription res ++ "\nUse --pattern '$0 == \"" ++ name ++ "\"' to rerun only this test"  }

main :: IO ()
main = defaultMainWithIngredients 
  [listingTests, modifyReporter appendPatternIfFailed consoleTestReporter] 
  tests 
```

1. `posprocessResult` is quite awkward. It would be much easier, if there was `consoleTestReportWithHook` accepting `hook :: TestName -> Result -> Result`. What do you think about it? I have another application for this in `tasty-bench`, namely https://github.com/Bodigrim/tasty-bench/blob/ddc1eecf125dd15d385afdd3a829993c367d0d2f/Test/Tasty/Bench.hs#L990. 

2. How crucial is to use `--pattern '$0 == "Full.Test.Name"'` and not just `--pattern Full.Escaped.Test.Name`? The former is extremely difficult to escape correctly within `cabal test --test-arguments '--hide-successes --pattern ...'`.

**Comment by feuerbach** [comment]
> It would be much easier, if there was consoleTestReportWithHook accepting hook :: TestName -> Result -> Result. What do you think about it?

Sure, let's have it.

> How crucial is to use --pattern '$0 == "Full.Test.Name"' and not just --pattern Full.Escaped.Test.Name? The former is extremely difficult to escape correctly within cabal test --test-arguments '--hide-successes --pattern ...'.

The latter may match more tests than intended.

That said, in the ingredient you have access to all the test names. So here's a fun thing you could do: figure out the smallest unique word that identifies the falling test. E.g. you could start with the last component of the test path; if that name occurs somewhere else, prepend the second to last, and so on. Not only will you avoid the `$0` business, but also generate much shorter commands.

**Comment by Bodigrim** [comment]
> So here's a fun thing you could do: figure out the smallest unique word that identifies the falling test.

Ah, nice! How much do we care about performance in this scenario?

**Comment by UnkindPartition** [comment]
Well, it should be unnoticeable on average test suites, and it shouldn't be prohibitively expensive on large ones.
