### ISSUE TITLE
Outdated links in README

### ISSUE THREAD

**Issue by DamienCassou** [UnkindPartition/tasty#297]
I'm learning Haskell and found that Tasty seems like a good tool to help me write my test suite. The README seems like enough to get me started. Nevertheless, the README contains many outdated links which makes me wonder if Tasty is still alive and if developers are still using it. The following lists outdated references in the README:

1. ["Other packages" section](https://github.com/UnkindPartition/tasty#other-packages)
    1. tasty-th: latest version is 0.1.7 from 2017
    2. tasty-hunit-adapter: from 2015
    3. tasty-discover: the link points to https://github.com/decentral1se/tasty-discover which points to https://git.coop/lwm/tasty-discover which points to https://git.coop/decentral1se/tasty-discover which contains

        > Archived project! Repository and other project resources are read only

        and no link to go to something that is still alive
2. ["Press" section](https://github.com/UnkindPartition/tasty#press)
    - all links are from 2013 to 2018

**Comment by UnkindPartition** [comment]
Hi Damien. Tasty is very much alive, and I rely on it daily, as do a lot of other people.

The only outdated link that I see here is for tasty-discover. I've now updated all github links to point to hackage instead, which should help with this kind of breakage when packages change hands. FWIW, the current github link for tasty-discover is https://github.com/haskell-works/tasty-discover.

Regarding third-party packages that haven't been updated for a while, it could be that they just continue working and there hasn't been a need in updates, or it could be that they are abandoned. You'll have to check for yourself and raise any issues with the corresponding authors. If you discover a truly abandoned package (one that doesn't build or work correctly with the recent versions of tasty and whose maintainers do not respond to issues), we should probably remove them from the README.

**Comment by DamienCassou** [comment]
Thank you for your answer. I don't think there is much more to do regarding this issue so I will close it. Feel free to open it again if you want to.
