### ISSUE TITLE
Generalizing tasty

### ISSUE THREAD

**Issue by adithyaov** [UnkindPartition/tasty#299]
Although `tasty` has been developed as a testing framework, a lot
of cool stuff has been built using its core functionality.

I was wonder if it's possible to abstract this further and remove
the idea of testing away from `tasty`. Is it possible to provide
the same functionality in an target agnostic manner?

Consider `tasty-bench` which is a pretty sweet benchmarking tool.

In `tasty-bench`,
```
...
bench = singleTest

bgroup = testGroup
...
```

Here, the word `test` is used in functions that are used to
define benchmarks. Is it possible to disassociate the word `test`
from functions that can be understood in a more general way?

I understand that `tasty` was meant to be a testing framework but
its clever usage in many libraries is evidence that there is a
hidden abstraction here. I'm wondering if its possible to make
that abstraction clear.

I don't have a lot of exprience with `tasty`. The text above
might make very little sense, if so feel free to close this
issue.

cc: @Bodigrim

**Comment by UnkindPartition** [comment]
Yeah, I'm not quite sure what you're after here to be honest.

Are you suggesting just renaming some of the functions?

Do you have other examples apart from tasty-bench that would warrant this?

**Comment by adithyaov** [comment]
> Are you suggesting just renaming some of the functions?

Yeah, that was basically a rant about renaming stuff and maybe
moving away from the prefix `Test`. Don't know if it is sensible.

> Do you have other examples apart from tasty-bench that would warrant this?

There are a lot of `tasty-*` packages, but most of them work on
improving the `test` experience.  I'm only aware of `tasty-bench`
that solves a different problem.

**Comment by UnkindPartition** [comment]
This seems to be a minor issue not worth breaking existing code, and it sounds like it's already solved on the tasty-bench's side.
