### ISSUE TITLE
Expose an alternative to `withResource` that allows to use `with-`-style functions

### ISSUE THREAD

**Issue by fghibellini** [UnkindPartition/tasty#302]
The issue is best explained on my [StackOverflow question](https://stackoverflow.com/q/67956499/3343425).

the TLDR is: [`withResource`](https://hackage.haskell.org/package/tasty-0.5.1/docs/Test-Tasty.html#v:withResource) doesn't allow you to use a resource exposed through a with-style function (i.e. one of type `(a -> IO b) -> IO b`) since it expects an resource allocation and cleanup function.

The issue arises even in primitive scenarios like testing a Servant application (Servant being one of the most popular web frameworks for Haskell).

I'm happy to try to implement this if it's of interest to the maintainers.

**Comment by UnkindPartition** [comment]
Hi Filippo, I responded at StackOverflow.

The TLDR is, I doubt you'd be able to implement such interface without breaking the existing functionality or resorting to the [threads trick](https://ro-che.info/articles/2019-07-19-decompose-contt). While the threads trick works well in practice, it's not bullet-proof, and I'm not eager to provide support for it as part of tasty.

**Comment by kindaro** [comment]
Hello Roman.

I had the exact same problem and I solved with the exact same threads trick. When you say that it is not bullet-proof, do you have in mind some specific failure modes? Do you imply that the bracket could run the continuation multiple times? Or something else?

**Comment by UnkindPartition** [comment]
Yeah, mostly the possibility that the continuation is run zero or multiple times, and also it probably reacts to exceptions slightly differently than the non-decomposed version.
