### ISSUE TITLE
Make an option to set quickcheck chatty option to true

### ISSUE THREAD

**Issue by coot** [UnkindPartition/tasty#306]
The [chatty](https://github.com/UnkindPartition/tasty/blob/master/quickcheck/Test/Tasty/QuickCheck.hs#L170) option, if set to `True`, displays a counter of the number of tests passed (or shrinks done) so far.  Sometimes it's useful, especially when executing a test with a large value of `--quickcheck-tests`.

**Comment by Bodigrim** [comment]
@coot are you happy to close? I imagine this is superseded by your work on progress reporting.

**Comment by coot** [comment]
Yes, this is obsolete now.
