### ISSUE TITLE
Print number of tests when no failures

### ISSUE THREAD

**Issue by yaitskov** [UnkindPartition/tasty#310]
Hi,

I found current behavior distracting, because when all specified tests pass - it is not clear
whether it is really green or I just made a typo in a regex pattern for test names I would like to run and run zero tests.

```shell
cabal test  --test-options "-p /Unuset/"
```

```
Running 1 test suites...
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to:
/home/dan/pro/dist-newstyle/build/x86_64-linux/ghc-8.10.6/napkin-0.3.8/t/spec/test/pro-0.3.8-spec.log
1 of 1 test suites (1 of 1 test cases) passed.

```

**Comment by Bodigrim** [comment]
It's not up to `tasty`; `cabal` suppresses successful test output unless invoked as
```
cabal test --test-show-details=direct
```

**Comment by yaitskov** [comment]
thanks
