### ISSUE TITLE
QuickCheckMaxShrinks isn't exported

### ISSUE THREAD

**Issue by wrengr** [UnkindPartition/tasty#316]
Everything about `QuickCheckMaxShrinks` is already defined (afaict), however unlike the other  options it's not exported for some reason

**Comment by UnkindPartition** [comment]
Thanks, should be fixed in tasty-1.4.2.1.

**Comment by wrengr** [comment]
Thanks :)

Since this is an API/export change, could you bump the version to 1.4.3 instead (and/or bump tasty-quickcheck to 0.10.2)?

**Comment by UnkindPartition** [comment]
Oops, I copy-pasted the wrong package for you (I released both at the same time). I did release it as tasty-quickcheck-0.10.2 :)
