### ISSUE TITLE
Drop dependency on `call-stack`

### ISSUE THREAD

**Issue by hasufell** [UnkindPartition/tasty#339]
I'm trying to use `tasty-hunit` in filepath in the test-suite, but `call-stack` itself depends on `filepath`, so I get circular imports.

The library doesn't seem necessary, so I suggest to drop it.

**Comment by Bodigrim** [comment]
Is it possible to rewrite your tests to use solely `tasty-quickcheck` instead of `tasty-hunit`? Cf. https://github.com/haskell/bytestring/commit/583cef086abcdff977b6787a15351aa4b88a4400

**Comment by hasufell** [comment]
Yes, I dropped all tasty dependencies and use raw QuickCheck directly.
