### ISSUE TITLE
Release tasty-1.4.3

### ISSUE THREAD

**Issue by Bodigrim** [UnkindPartition/tasty#355]
I'd like to have a release of `tasty` including #346, #345 and #344. Unfortunately `master` branch includes a breaking change from #340, but I'd rather wait for #343 to land before making a major version bump.

So I suggest we create a release branch from `master`, revert #343 there and release `tasty-1.4.3`. If no one objects, I can do it myself, but I lack Hackage rights. Happy to make a branch and let someone (@andreasabel?) to upload.

**Comment by andreasabel** [comment]
I second this plan.
@Bodigrim, I added you to the package uploaders of `tasty`; you will need the rights even to upload a candidate.

**Comment by Bodigrim** [comment]
Released: https://hackage.haskell.org/package/tasty-1.4.3

Comparison: https://github.com/UnkindPartition/tasty/compare/core-1.4.2.3...core-1.4.3
