### ISSUE TITLE
Possibly unintended change in `tasty-1.5`

### ISSUE THREAD

**Issue by andreasabel** [UnkindPartition/tasty#395]
Looking through the [changes between 1.4.3 and 1.5](https://github.com/UnkindPartition/tasty/compare/core-1.4.3...core-1.5) I noticed a strange commit: https://github.com/UnkindPartition/tasty/commit/8043c0cddc59e6ae389e2dfb52b20d0543b76a28
It is labelled "clean code" but it does change
```haskell
when nonempty $ do printHeading :: IO (); getTraversal printBody
```
to
```haskell
when nonempty $ printHeading
getTraversal printBody
```
A priori, this is not just a cleaning, but it is a semantic change, invoking `getTraversal printBody` now even when `not nonempty`.  (I am getting _heartbleed_ vibes here.)

Questions:
- Was this change intended?  ATTN: @coot 
- Is this change observable?

**Comment by coot** [comment]
I replied in [the commit](https://github.com/UnkindPartition/tasty/commit/8043c0cddc59e6ae389e2dfb52b20d0543b76a28#r130572324).

**Comment by andreasabel** [comment]
I assign you to this issue, if that is ok with you, @coot.

**Comment by coot** [comment]
That's perfectly fine.
