### ISSUE TITLE
Should `unix` flag be manual?

### ISSUE THREAD

**Issue by phadej** [UnkindPartition/tasty#418]
As far as I can tell, if `unix-2.9` is released, the signal installation will be silently turned off.

It might be intentional, but then a comment would be nice.

OTOH, is there a reason to simply depend on `unix` unconditionally, on unixes.

**Comment by Bodigrim** [comment]
The reason is to avoid circular dependencies when testing `bytestring` and `unix` themselves. 

I'm fairly sure I'll notice `unix-2.9` release happening to bump bound.

**Comment by phadej** [comment]
> The reason is to avoid circular dependencies when testing

The flag can still be manual, and be set when testring `bytestring` and `unix`, can't it?

**Comment by Bodigrim** [comment]
My experience is that it's valuable to lower barriers to contribute to `bytestring` and `unix`. Users should be able to do `cabal unpack bytestring && cd bytestring-* && cabal test` without having to guess manual flags. 

I don't feel like not installing handlers in some extreme build configurations is a big deal. If anything, I'm more inclined to remove the upper bound for `unix` to eliminate a potential disruption when `unix-2.9` is out.
