### ISSUE TITLE
Provide QuickCheck input values in case of non-termination

### ISSUE THREAD

**Issue by noschinl** [UnkindPartition/tasty#86]
When a QuickCheck test runs into a timeout, Tasty does not report the input values generated by QuickCheck for the interrupted run. These are interesting in case the test triggered a non-terminating behaviour.

QuickCheck itself can provide this information if the test is interrupted by a UserException (i.e., Ctrl-C).

**Comment by osa1** [comment]
Came here to open this issue.. This feature would be really awesome.

**Comment by grayjay** [comment]
Printing the replay message before running the test when --quickcheck-show-replay is true would also help with debugging non-terminating runs.

**Comment by Bodigrim** [comment]
Duplicate of https://github.com/UnkindPartition/tasty/issues/359.

**Comment by Bodigrim** [comment]
Closing, let's continue discussion in #359.
